### ISSUE TITLE
ERROR:root:'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by dspv** [cevoaustralia/aws-google-auth#217]
### Environment
MacOS: 11.2
Python 3.9.1

### Error
```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/google.py", line 325, in do_login
    sess = self.handle_prompt(sess)
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/google.py", line 620, in handle_prompt
    response_page.find('input', {
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dspv** [comment]
Worked on MacOS 11.1 version
After update to 11.2 worked VERY SLOWLY
After reboot stoped working :-(

**Comment by dspv** [comment]
Solved

**Comment by jpedrobf** [comment]
@dspv Hi, have you done anything to solve it? I'm facing the same and can't find a way around it :(
